### ISSUE TITLE
installing in ubuntu 20.04 with python3.9

### ISSUE THREAD

**Issue by yamifm0f** [drunsinn/pyXSteam#5]
I tried the installation that you explained but got this error 

Traceback (most recent call last):
  File "/home/faisal/Downloads/pyXSteam-master/setup.py", line 4, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'

setuptools are already installed so this error seems odd to me

**Comment by drunsinn** [comment]
Have you tried installing pyXSteam via pip?
I just checked Ubuntu 20.04 Server (Python 3.8.5), macOS 11.0.1 (Python 3.9) and Raspian (Python 3.7) and all install just fine via pip.
Have you checked if the setup tool are installed for the correct python version?  Ubuntu has, as far as I know, Python 2 as well as Python 3.

**Comment by yamifm0f** [comment]
it is rather difficult to explain but I want to use pyXSteam through python --enable-shared. I did install pyXSteam through pip install pyxsteam and in the regular use it works fine but I need to also install it through sudo apt-get install python3-library_name to be able to use it with the python shared library. I use python with other programs that calls python packages through the --enable-shared options.

**Comment by drunsinn** [comment]
Ok, I will look into what is required to make this work. Can you give me an example of a python package for which this works?
A quick google-search shows some people recommending `sudo apt-get install -y python3-setuptools` but this is probably not what you want?

**Comment by yamifm0f** [comment]
@drunsinn Thank you. well the sudo apt-get install python3-numpy and most commonly used packages like SciPy etc. I have tried sudo apt-get install -y python3-setuptools but it comes up as setuptools are already installed. that is with pyXSteam recommended installation setup.py right? yeah it does not work. I think that the only way to make pyXSteam installed into the library is with this command sudo apt-get install python3-numpy

**Comment by drunsinn** [comment]
can you check with #8 if this fixes your problem? It seems setuptools is still not part of the the python standard library. With the fallback to distuils it should hopefully work

**Comment by yamifm0f** [comment]
I am sorry but it did not work for me. did you try it?

**Comment by drunsinn** [comment]
I check if it was possible to run the setup on a blank python installation without the setup tools package. My steps to verify were:

1. create vent without pip and setup tools: `python3 -m venv --without-pip . `
2. activate venv with `source bin/activate`
3. check if setuptools are really missing by trying `import setuptools` in the python interpreter which fails
4. clone branch with my changes `git clone --branch distutils_fallback git@github.com:drunsinn/pyXSteam.git`
5. install pyXSteam with `python3 setup.py install`
Running the setup I can see that it uses the distutils library.

Did the behavior change in any way with my changes? Can you check if you are using the setup.py from my branch? I didn't commit the changes to master yet.

**Comment by drunsinn** [comment]
@yamifm0f can you give me an update on the situation?
I have not been able to figure out what the problem might be. Can you maybe describe how I can set up and use the environment you are using so I can reproduce the error myself?

**Comment by drunsinn** [comment]
@yamifm0f any updates on the current situation?

**Comment by yamifm** [comment]
Hi @drunsinn sorry for the late reply.  Unfortunately I do not use any environment. I use the direct python installation and pip to do everything. With the default python (3.8 ) in 20.04 I can just use pip to install pyXsteam and it can be called from the shared library like other packages.  but if I install any other version of python with the —enabled share installation I can not not call pyxsteam using the shared library (yes I can call it in the regular way only)

**Comment by drunsinn** [comment]
Hi!
By environment I meant any steps I can follow to create the situation you are working on. From your last comment I gather you are compiling python yourself? AFAIK The compile option `--enabled share` should only affect the way the python interpreter. I might ignorant but I don't see any reason why it should relate to importing/installing library. 
The error you mentioned relates to the fact that Python can't finde the `setuptools` library. With my change on the new branch I dropped the requirement for `setuptools` during the install process by using `distutils` instead. Please note that these changes are currently only available in the branch and not via pip.
On my Ubuntu machine every version of python is installed in a separate folder under /usr/lib. Each version has a separate set of library's and module's. Your system probably has a `setuptools` library for python3.8 but not for 3.9 which is why it can't find the library.
`pyXSteam` itself has no dependency besides the standard library. `Numpy` is only necessary if you want to run the tests.

**Comment by drunsinn** [comment]
I have integrated the fallback and will be releasing a new version later today.

If your problem is not fixed, feel free to reopen this issue or create a new one.
